version: 2.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0     
    working_directory: ~/repo
    steps:
      - checkout     
      - run:
          name: Run Tests User Blog API 
          command: mvn clean verify

      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
